export const list: ([string, string, boolean] | [string, string])[] = [
    ['Domains', 'v3x.domains'],
    ['Company', 'v3x.company'],
    ['Articles & Writing', 'v3x.blog', false],
    ['Community', 'v3x.community', false],
    ['Foundation', 'v3x.foundation', false],
    ['Page Components', 'v3x.style', false],
    ['Branding & Mediakit', 'v3x.design', false],
    ['Health & Status', 'v3x.health'],
    ['Discord', 'v3x.chat', false],
    ['Email', 'v3x.email', false],
    ['Contact', 'v3x.contact', false],
    ['Unknown', 'v3x.computer'],
    ['Unknown', 'v3x.zone'],
    ['Unknown', 'v3x.world'],
    ['Unknown', 'v3x.tools'],
    ['Unknown', 'v3x.today'],
    ['Unknown', 'v3x.team'],
    ['Unknown', 'v3x.systems'],
    ['Unknown', 'v3x.solutions'],
    ['Unknown', 'v3x.holdings'],
    ['Unknown', 'v3x.fyi'],
    ['Unknown', 'v3x.digital'],
    ['Unknown', 'v3x.wiki'],
    ['Unknown', 'v3x.works'],
    ['Unknown', 'v3x.group'],
    ['Unknown', 'v3x.shop'],
    ['Unknown', 'v3x.space'],
    ['Unknown', 'v3x.lol'],
    ['Unknown', 'v3x.quest'],
    ['Unknown', 'v3x.bio'],
    ['Unknown', 'v3x.info'],
    ['Unknown', 'v3x.gay'],
    ['Unknown', 'v3x.finance'],
    ['Unknown', 'v3x.pics'],
    ['Unknown', 'v3x.sex'],
    ['Unknown', 'v3x.legal'],
    ['Unknown', 'v3x.industries'],
    ['Unknown', 'v3x.gallery'],
    ['Unknown', 'v3x.fund'],
    ['Unknown', 'v3x.events'],
    ['Unknown', 'v3x.day'],
    ['Unknown', 'v3x.host'],
    ['Unknown', 'v3x.fm'],
    ['Unknown', 'v3x.cash'],
    ['Unknown', 'v3x.art'],
    ['Unknown', 'v3x.work'],
    ['Unknown', 'v3x.vote'],
    ['Unknown', 'v3x.video'],
    ['Unknown', 'v3x.uk'],
    ['Unknown', 'v3x.university'],
    ['Unknown', 'v3x.technology'],
    ['Unknown', 'v3x.support'],
    ['Unknown', 'v3x.studio'],
    ['Unknown', 'v3x.software'],
    ['Unknown', 'v3x.social'],
    ['Unknown', 'v3x.show'],
    ['Unknown', 'v3x.sh'],
    ['Unknown', 'v3x.school'],
    ['Unknown', 'v3x.run'],
    ['Unknown', 'v3x.rsvp'],
    ['Unknown', 'v3x.restaurant'],
    ['Unknown', 'v3x.report'],
    ['Unknown', 'v3x.property'],
    ['Unknown', 'v3x.place'],
    ['Unknown', 'v3x.pizza'],
    ['Unknown', 'v3x.pictures'],
    ['Unknown', 'v3x.photos'],
    ['Unknown', 'v3x.pet'],
    ['Unknown', 'v3x.partners'],
    ['Unknown', 'v3x.observer'],
    ['Unknown', 'v3x.news'],
    ['Unknown', 'v3x.name'],
    ['Unknown', 'v3x.network'],
    ['Unknown', 'v3x.money'],
    ['Unknown', 'v3x.media'],
    ['Unknown', 'v3x.limo'],
    ['Unknown', 'v3x.limited'],
    ['Unknown', 'v3x.lighting'],
    ['Unknown', 'v3x.land'],
    ['Unknown', 'v3x.kitchen'],
    ['Unknown', 'v3x.in'],
    ['Unknown', 'v3x.holiday'],
    ['Unknown', 'v3x.house'],
    ['Unknown', 'v3x.games'],
    ['Unknown', 'v3x.flights'],
    ['Unknown', 'v3x.fish'],
    ['Unknown', 'v3x.fan'],
    ['Unknown', 'v3x.family'],
    ['Unknown', 'v3x.fail'],
    ['Unknown', 'v3x.expert'],
    ['Unknown', 'v3x.exchange'],
    ['Unknown', 'v3x.equipment'],
    ['Unknown', 'v3x.enterprises'],
    ['Unknown', 'v3x.engineer'],
    ['Unknown', 'v3x.energy'],
    ['Unknown', 'v3x.education'],
    ['Unknown', 'v3x.earth'],
    ['Unknown', 'v3x.dog'],
    ['Unknown', 'v3x.directory'],
    ['Unknown', 'v3x.delivery'],
    ['Unknown', 'v3x.degree'],
    ['Unknown', 'v3x.dating'],
    ['Unknown', 'v3x.country'],
    ['Unknown', 'v3x.cool'],
    ['Unknown', 'v3x.consulting'],
    ['Unknown', 'v3x.coffee'],
    ['Unknown', 'v3x.codes'],
    ['Unknown', 'v3x.church'],
    ['Unknown', 'v3x.city'],
    ['Unknown', 'v3x.camera'],
    ['Unknown', 'v3x.capital'],
    ['Unknown', 'v3x.bike'],
    ['Unknown', 'v3x.auction'],
    ['Unknown', 'v3x.army'],
    ['Unknown', 'v3x.apartments'],
    ['Unknown', 'v3x.agency'],
    ['Unknown', 'v3x.college'],
    ['Unknown', 'v3x.build'],
    ['Unknown', 'v3x.website'],
    ['Unknown', 'v3x.store'],
    ['Unknown', 'v3x.site'],
    ['Unknown', 'v3x.rent'],
    ['Unknown', 'v3x.monster'],
    ['Unknown', 'v3x.mom'],
    ['Unknown', 'v3x.hair'],
    ['Unknown', 'v3x.fun'],
    ['Unknown', 'v3x.cards'],
    ['Unknown', 'v3x.markets'],
    ['Unknown', 'v3x.wtf'],
];

export const list_total = list.length;

// export const list_used = list
//     .filter((item) => item[0] !== 'Unknown')
//     .sort((a, b) => a[0].localeCompare(b[0]));
// export const list_unknown = list
//     .filter((item) => item[0] === 'Unknown')
//     .sort((a, b) => a[1].localeCompare(b[1]));

// the above but instead of sorted alphabetically, sorted by length and if lengths are the same alphabetically

export const list_used = list.filter((item) => item[0] !== 'Unknown');

export const list_unknown = list
    .filter((item) => item[0] === 'Unknown')
    .sort((a, b) => {
        if (a[1].length > b[1].length) {
            return 1;
        } else if (a[1].length < b[1].length) {
            return -1;
        } else {
            return a[1].localeCompare(b[1]);
        }
    });
